#
# GNUmakefile - Generated by ProjectCenter
#
ifeq ($(GNUSTEP_MAKEFILES),)
 GNUSTEP_MAKEFILES := $(shell gnustep-config --variable=GNUSTEP_MAKEFILES 2>/dev/null)
endif
ifeq ($(GNUSTEP_MAKEFILES),)
 $(error You need to set GNUSTEP_MAKEFILES before compiling!)
endif

include $(GNUSTEP_MAKEFILES)/common.make

#
# Tool
#
VERSION = 0.1
PACKAGE_NAME = kobjcEngine
TOOL_NAME = kobjcEngine
objcTest_TOOL_ICON = 


#
# Resource files
#
kobjcEngine_RESOURCE_FILES = \
Resources/Version \


#
# Header files
#
kobjcEngine_HEADER_FILES = \


#
# Class files
#
kobjcEngine_OBJC_FILES = \


#
# Other sources
#
kobjcEngine_OBJC_FILES += \
demo/main.m

#
# Makefiles
#
-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/tool.make
-include GNUmakefile.postamble
